[build]
  # Definer hvilken kommando som skal brukes for å bygge prosjektet.
  publish = "build"
  command = "npm run build"

[dev]
  # Hvis du bruker netlify dev, kan du spesifisere hvilken port `npm start` vil kjøre på.
  # Dette er typisk port 3000 for mange React/Node.js prosjekter, men det kan variere.
  port = 3000
