[build]
command = "npm install && npm run build"  # Build command for client
publish = "build"  # Folder where the client build files are located


[dev]
  # Hvis du bruker netlify dev, kan du spesifisere hvilken port `npm start` vil kjøre på.
  # Dette er typisk port 3000 for mange React/Node.js prosjekter, men det kan variere.
  port = 3000
