[build]
command = "npm install && npm run build"  # If you need to run a build step for the server
publish = "build"  # Publish the built functions to this directory

[functions]
directory = "functions" 